// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import "IReactContext.idl";

#include "NamespaceRedirect.h"

namespace Microsoft.ReactNative {

  [default_interface]
  [webhosthidden]
  runtimeclass XamlUIService {
    static XamlUIService FromContext(IReactContext context);

    XAML_NAMESPACE.DependencyObject ElementFromReactTag(Int64 reactTag);

    // Dispatch UI event. This method is to be moved to IReactViewContext.
    void DispatchEvent(XAML_NAMESPACE.FrameworkElement view, String eventName, JSValueArgWriter eventDataArgWriter);

    // This needs to be manually provided to the ReactInstanceSettings when using XamlIslands
    static void SetXamlRoot(IReactPropertyBag properties, XAML_NAMESPACE.XamlRoot xamlRoot);
    // This needs to be manually provided to the ReactInstanceSettings when using XamlIslands
    static void SetAccessibleRoot(IReactPropertyBag properties, XAML_NAMESPACE.FrameworkElement accessibleRoot);
    static XAML_NAMESPACE.XamlRoot GetXamlRoot(IReactPropertyBag properties);
    static XAML_NAMESPACE.FrameworkElement GetAccessibleRoot(IReactPropertyBag properties);

    static UInt64 GetIslandWindowHandle(IReactPropertyBag properties);
    static void SetIslandWindowHandle(IReactPropertyBag properties, UInt64 windowHandle);
  }
} // namespace Microsoft.ReactNative
